# Generated by Django 6.0 on 2026-01-06 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_area', models.CharField(choices=[('career', 'Career/Finance'), ('health', 'Health/Wellness'), ('relationships', 'Relationships'), ('personal_growth', 'Personal Growth'), ('fun_recreation', 'Fun/Recreation'), ('home_family', 'Home/Family'), ('contribution', 'Contribution/Service'), ('spirituality', 'Spirituality')], help_text='Life area this goal belongs to', max_length=20)),
                ('title', models.CharField(help_text='Goal title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('target_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', help_text='Current goal status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short bio or personal statement')),
                ('coaching_focus', models.CharField(blank=True, help_text='Main area of personal development focus', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='VisionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the vision board', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('elements', models.JSONField(default=list, help_text='List of board elements with positions and content')),
                ('is_active', models.BooleanField(default=True, help_text='Is this board currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vision Board',
                'verbose_name_plural': 'Vision Boards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Life Assessment', help_text='Name for this assessment', max_length=200)),
                ('career', models.IntegerField(help_text='Career/Finance satisfaction (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('health', models.IntegerField(help_text='Health/Wellness satisfaction (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('relationships', models.IntegerField(help_text='Relationships satisfaction (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('personal_growth', models.IntegerField(help_text='Personal Growth satisfaction (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('fun_recreation', models.IntegerField(help_text='Fun/Recreation satisfaction (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('home_family', models.IntegerField(help_text='Home/Family satisfaction (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('contribution', models.IntegerField(help_text='Contribution/Service satisfaction (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('spirituality', models.IntegerField(help_text='Spirituality satisfaction (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes or reflections')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wheel Assessment',
                'verbose_name_plural': 'Wheel Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
