# Generated by Django 6.0 on 2026-01-06 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionboard',
            name='elements',
        ),
        migrations.CreateModel(
            name='VisionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Text Snippet'), ('image', 'Image'), ('quote', 'Quote')], default='text', max_length=10)),
                ('title', models.CharField(blank=True, help_text='Optional title for the element', max_length=200)),
                ('content', models.TextField(help_text='Text content or image alt text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vision_elements/')),
                ('color', models.CharField(default='#ffffff', help_text='Background color (hex)', max_length=7)),
                ('font_size', models.IntegerField(default=16, help_text='Font size in pixels')),
                ('text_color', models.CharField(default='#000000', help_text='Text color (hex)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_elements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vision Element',
                'verbose_name_plural': 'Vision Elements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisionBoardElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.IntegerField(default=0, help_text='X coordinate on board')),
                ('y_position', models.IntegerField(default=0, help_text='Y coordinate on board')),
                ('width', models.IntegerField(default=200, help_text='Element width in pixels')),
                ('height', models.IntegerField(default=150, help_text='Element height in pixels')),
                ('z_index', models.IntegerField(default=0, help_text='Stacking order')),
                ('rotation', models.IntegerField(default=0, help_text='Rotation in degrees')),
                ('vision_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_elements', to='coaching.visionboard')),
                ('vision_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.visionelement')),
            ],
            options={
                'verbose_name': 'Board Element',
                'verbose_name_plural': 'Board Elements',
                'unique_together': {('vision_board', 'vision_element')},
            },
        ),
        migrations.AddField(
            model_name='visionboard',
            name='elements',
            field=models.ManyToManyField(blank=True, help_text='Elements placed on this board', related_name='boards', through='coaching.VisionBoardElement', to='coaching.visionelement'),
        ),
    ]
