# Generated by Django 6.0 on 2026-01-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_remove_visionboard_elements_visionelement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visionboardelement',
            options={},
        ),
        migrations.AddField(
            model_name='visionboard',
            name='vision_elements',
            field=models.ManyToManyField(blank=True, help_text='Elements placed on this board', related_name='boards', through='coaching.VisionBoardElement', to='coaching.visionelement'),
        ),
        migrations.RemoveField(
            model_name='visionboard',
            name='elements',
        ),
        migrations.AddField(
            model_name='visionboard',
            name='elements',
            field=models.JSONField(default=list, help_text='List of board elements with positions and content'),
        ),
    ]
