# Generated by Django 6.0 on 2026-01-06 16:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_alter_visionboardelement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelassessment',
            name='career',
        ),
        migrations.RemoveField(
            model_name='wheelassessment',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='wheelassessment',
            name='fun_recreation',
        ),
        migrations.RemoveField(
            model_name='wheelassessment',
            name='health',
        ),
        migrations.RemoveField(
            model_name='wheelassessment',
            name='home_family',
        ),
        migrations.RemoveField(
            model_name='wheelassessment',
            name='personal_growth',
        ),
        migrations.RemoveField(
            model_name='wheelassessment',
            name='relationships',
        ),
        migrations.RemoveField(
            model_name='wheelassessment',
            name='spirituality',
        ),
        migrations.CreateModel(
            name='WheelArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Area name (e.g., Career, Health)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('color', models.CharField(default='#4F46E5', help_text='Hex color code', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_default', models.BooleanField(default=False, help_text='System default area')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wheel Area',
                'verbose_name_plural': 'Wheel Areas',
                'ordering': ['order', 'created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WheelAssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Satisfaction score (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.wheelarea')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='coaching.wheelassessment')),
            ],
            options={
                'unique_together': {('assessment', 'area')},
            },
        ),
    ]
