# Generated by Django 6.0 on 2026-01-06 16:43

from django.db import migrations


def create_default_wheel_areas(apps, schema_editor):
    """Create default wheel areas for all existing users"""
    User = apps.get_model('auth', 'User')
    WheelArea = apps.get_model('coaching', 'WheelArea')

    defaults = [
        ('Career/Finance', '#4F46E5', 'Professional and financial satisfaction'),
        ('Health/Wellness', '#10B981', 'Physical and mental health'),
        ('Relationships', '#F59E0B', 'Personal relationships and connections'),
        ('Personal Growth', '#EF4444', 'Learning and self-development'),
        ('Fun/Recreation', '#8B5CF6', 'Leisure and entertainment'),
        ('Home/Family', '#06B6D4', 'Home environment and family life'),
        ('Contribution/Service', '#84CC16', 'Community involvement and giving'),
        ('Spirituality', '#F97316', 'Spiritual and life purpose'),
    ]

    for user in User.objects.all():
        for i, (name, color, description) in enumerate(defaults):
            WheelArea.objects.create(
                user=user,
                name=name,
                description=description,
                color=color,
                order=i,
                is_default=True
            )


def migrate_existing_assessment_data(apps, schema_editor):
    """Migrate existing wheel assessment data to new structure"""
    WheelAssessment = apps.get_model('coaching', 'WheelAssessment')
    WheelArea = apps.get_model('coaching', 'WheelArea')
    WheelAssessmentScore = apps.get_model('coaching', 'WheelAssessmentScore')

    # This migration assumes the old fields still exist temporarily
    # Since we removed them in 0004, we need to use raw SQL to access old data
    # For now, we'll create empty assessments - in production, you'd need to
    # modify the migration order or use raw SQL

    # For development, just ensure default areas exist
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_remove_wheelassessment_career_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_wheel_areas, migrations.RunPython.noop),
        migrations.RunPython(migrate_existing_assessment_data, migrations.RunPython.noop),
    ]
