# Generated by Django 6.0 on 2026-01-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_migrate_wheel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='wheel_area',
            field=models.ForeignKey(help_text='Life area this goal belongs to', on_delete=django.db.models.deletion.CASCADE, to='coaching.wheelarea'),
        ),
    ]
