# Generated by Django 6.0 on 2026-01-06 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0006_alter_goal_wheel_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionElementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('color', models.CharField(default='#4F46E5', help_text='Category color (hex)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_element_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vision Element Category',
                'verbose_name_plural': 'Vision Element Categories',
                'ordering': ['order', 'created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='visionelement',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this element belongs to', related_name='vision_elements', to='coaching.visionelementcategory'),
        ),
    ]
