# Generated by Django 6.0 on 2026-01-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0007_visionelementcategory_visionelement_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionBoardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('template_data', models.JSONField(default=dict, help_text='Template structure with default elements and layout')),
                ('is_default', models.BooleanField(default=False, help_text='System default template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vision Board Template',
                'verbose_name_plural': 'Vision Board Templates',
            },
        ),
        migrations.AddField(
            model_name='visionboard',
            name='related_goal',
            field=models.ForeignKey(blank=True, help_text='Goal this vision board is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_boards', to='coaching.goal'),
        ),
    ]
